In [ ]:
# Task 19: Filter Dataset Records

## Objective
Filter records from a dataset using one or more conditions
with Pandas.

## Deliverables
- At least three filtering examples
- Filtered DataFrames
- Explanation of each condition
- Number of records returned by each filter

In [1]:
import pandas as pd
import numpy as np

data = {
    "student_id": [
        1001, 1002, 1003, 1004, 1005, 1006,
        1007, 1008, 1009, 1010, 1011, 1012
    ],
    "name": [
        "Aarav", "Diya", "Kabir", "Ananya",
        "Ishaan", "Meera", "Rohan", "Sara",
        "Vivaan", "Aditi", "Arjun", "Nisha"
    ],
    "department": [
        "Computer Science", "Electronics", "Mechanical",
        "Computer Science", "Civil", "Electronics",
        "Mechanical", "Computer Science", "Civil",
        "Electronics", "Mechanical", "Computer Science"
    ],
    "age": [20, 21, 20, 22, 21, 20, 22, 21, 20, 22, 21, 20],
    "marks": [86, 91, 74, 95, 68, 88, 79, 93, 72, 84, 77, 90],
    "attendance": [92, 88, 79, 96, 72, 90, 85, 94, 80, 86, 75, 91]
}

df = pd.DataFrame(data)

print("Student dataset created successfully.")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

display(df)

Student dataset created successfully.
Number of rows: 12
Number of columns: 6

    student_id    name        department  age  marks  attendance
0         1001   Aarav  Computer Science   20     86          92
1         1002    Diya       Electronics   21     91          88
2         1003   Kabir        Mechanical   20     74          79
3         1004  Ananya  Computer Science   22     95          96
4         1005  Ishaan             Civil   21     68          72
5         1006   Meera       Electronics   20     88          90
6         1007   Rohan        Mechanical   22     79          85
7         1008    Sara  Computer Science   21     93          94
8         1009  Vivaan             Civil   20     72          80
9         1010   Aditi       Electronics   22     84          86
10        1011   Arjun        Mechanical   21     77          75
11        1012   Nisha  Computer Science   20     90          91

In [2]:
print("EXAMPLE 1: STUDENTS WITH MARKS >= 85")

filter_marks = df[df["marks"] >= 85]

display(filter_marks)

print("Number of matching records:", len(filter_marks))

EXAMPLE 1: STUDENTS WITH MARKS >= 85

    student_id    name        department  age  marks  attendance
0         1001   Aarav  Computer Science   20     86          92
1         1002    Diya       Electronics   21     91          88
3         1004  Ananya  Computer Science   22     95          96
5         1006   Meera       Electronics   20     88          90
7         1008    Sara  Computer Science   21     93          94
11        1012   Nisha  Computer Science   20     90          91

Number of matching records: 6

In [3]:
print("EXAMPLE 2: MARKS >= 80 AND ATTENDANCE >= 85")

filter_multiple = df[
    (df["marks"] >= 80) &
    (df["attendance"] >= 85)
]

display(filter_multiple)

print("Number of matching records:", len(filter_multiple))

EXAMPLE 2: MARKS >= 80 AND ATTENDANCE >= 85

    student_id    name        department  age  marks  attendance
0         1001   Aarav  Computer Science   20     86          92
1         1002    Diya       Electronics   21     91          88
3         1004  Ananya  Computer Science   22     95          96
5         1006   Meera       Electronics   20     88          90
7         1008    Sara  Computer Science   21     93          94
9         1010   Aditi       Electronics   22     84          86
11        1012   Nisha  Computer Science   20     90          91

Number of matching records: 7

In [4]:
print("EXAMPLE 3: MARKS >= 90 OR ATTENDANCE >= 95")

filter_or = df[
    (df["marks"] >= 90) |
    (df["attendance"] >= 95)
]

display(filter_or)

print("Number of matching records:", len(filter_or))

EXAMPLE 3: MARKS >= 90 OR ATTENDANCE >= 95

    student_id    name        department  age  marks  attendance
1         1002    Diya       Electronics   21     91          88
3         1004  Ananya  Computer Science   22     95          96
7         1008    Sara  Computer Science   21     93          94
11        1012   Nisha  Computer Science   20     90          91

Number of matching records: 4

In [5]:
print("EXAMPLE 4: COMPUTER SCIENCE STUDENTS WITH MARKS >= 90")

filter_department = df[
    (df["department"] == "Computer Science") &
    (df["marks"] >= 90)
]

display(filter_department)

print("Number of matching records:", len(filter_department))

EXAMPLE 4: COMPUTER SCIENCE STUDENTS WITH MARKS >= 90

    student_id    name        department  age  marks  attendance
3         1004  Ananya  Computer Science   22     95          96
7         1008    Sara  Computer Science   21     93          94
11        1012   Nisha  Computer Science   20     90          91

Number of matching records: 3

In [6]:
summary = pd.DataFrame({
    "Filtering Example": [
        "Marks >= 85",
        "Marks >= 80 AND attendance >= 85",
        "Marks >= 90 OR attendance >= 95",
        "Computer Science AND marks >= 90"
    ],
    "Matching Records": [
        len(filter_marks),
        len(filter_multiple),
        len(filter_or),
        len(filter_department)
    ]
})

display(summary)

                  Filtering Example  Matching Records
0                       Marks >= 85                 6
1  Marks >= 80 AND attendance >= 85                 7
2   Marks >= 90 OR attendance >= 95                 4
3  Computer Science AND marks >= 90                 3

In [7]:
df.to_csv("student_performance.csv", index=False)

print("student_performance.csv created successfully.")

student_performance.csv created successfully.

In [8]:
from google.colab import files

files.download("student_performance.csv")